### ISSUE TITLE
Request to add a preview image in the README

### ISSUE THREAD

**Issue by Lucas-C** [cucumber/github-issue-stats#3]
Hi

Your project looks interesting, but could you provide a preview / screenshot of the resulting output in your README please ?

**Comment by aslakhellesoy** [comment]
Hi @Lucas-C I haven’t used this in a while. Is there something wrong with the code? Is it not working for you?

**Comment by Lucas-C** [comment]
I don't now really :)
To be honest I didn't try it. I was looking for a tool that could display some statistics on a repo _issues_ & _PRs_. I stumbled upon yours, but without any image indicating what it produces, I did not take the time to test it.
I just thought it'd be worth opening an issue here suggesting to perhaps add an image to the README, maybe showing this_simplified Cumulative Flow Diagram_ that it mentions, in order to make this repo more appealing.
Feel free to close this if it doesn't seem to worth it to you.
